@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 04 13:45:09 -0500 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB_RCA_4bits_behav -key {Behavioral:sim_1:Functional:TB_RCA_4bits} -tclbatch TB_RCA_4bits.tcl -view C:/Users/Clark Simpler/School/UT Fall 2022/EE 316/Lab_5/Part 1/TB_RCA_4bits_behav.wcfg -log simulate.log"
call xsim  TB_RCA_4bits_behav -key {Behavioral:sim_1:Functional:TB_RCA_4bits} -tclbatch TB_RCA_4bits.tcl -view C:/Users/Clark Simpler/School/UT Fall 2022/EE 316/Lab_5/Part 1/TB_RCA_4bits_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
